In [ ]:
#Numpy-Numerical Python
1.What? Library
2.Data Analytics
3.What is its feature? Data Structure-n-Dimensional array
It performs mathematical and perform matrix operations easily

In [ ]:
[1] - 1D
[1 2 3] 1 row and 3 column = 3D

In [1]:
#Why Numpy??

#1.Memory usage!
#2.Convenient
#3.Faster
import numpy as np
import time
import sys


# 1.Memory usage!

In [4]:
#creating a numpy array
numpy_array = np.arange(100)
#in numpy it is arange instead of range
print("size of Numpy array ",(numpy_array.size * numpy_array.itemsize))

size of Numpy array  400


In [7]:
l=range(0,100)
print("size of List ",sys.getsizeof(1) * len(l))

size of List  2800


# 2.Convenient

In [8]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a1+a2

array([2, 4, 6, 8])

In [ ]:
'''
!pip install numpy
conda instal numpy --y
!pip3 install numpy


anaconda by default has numpy

'''

In [9]:
import numpy as np
arr=np.array([1,2,3,'Inceptez'])
print(type(arr[0]))

<class 'numpy.str_'>


In [11]:
print(np.__version__)

1.19.2


In [16]:
arr_2d=np.array([[1,2,3],[1,2,3]])
print(arr_2d)
print(arr_2d.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [18]:
#Functions involved in creating an array!

In [21]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a.reshape((4,4))
a.reshape((8,2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
a=np.array([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a.reshape((4,4))


ValueError: cannot reshape array of size 15 into shape (4,4)

In [24]:
#Linspace: This function create elements which are equally spaced from each other
#(start stop ,count of numbers it has to generate from starting and ending included)

np.linspace(0,100,5)
#output is in decimals

array([  0.,  25.,  50.,  75., 100.])

In [27]:
np.linspace(0,100,5)


NameError: name 'false' is not defined

In [25]:
#Arange
np.arange?
'''
arange([start,] stop[, step,], dtype=None)

'''
#Genrates values based on the step specified

In [26]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
#Square Matrix

#When no.of rows=no.of columns
#Identity matrix=diagonal matrix are 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
#Anti diagonal matrix
np.eye(3)[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [31]:
np.eye(4,k=4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros(2)

array([0., 0.])

In [37]:
#Operations with numpy
arr=np.array([20,30,40])
dup=arr.view()
arr[0]=60
print(arr)
print(dup)

[60 30 40]
[60 30 40]


In [39]:
#Iterations
#For loops
for i in arr:
    print(i)

60
30
40


In [ ]:
#1D- 1 loop
#2D- 2 loops
#3D- 3loops

In [40]:
arr_3d=np.array([[[1,3,5],[2,4,6],[5,6,7]]])

In [41]:
arr_3d

array([[[1, 3, 5],
        [2, 4, 6],
        [5, 6, 7]]])

In [42]:
arr_3d.shape
#1 room, 3x3 elements


(1, 3, 3)

In [43]:
for i in arr_3d:
    print(i)

[[1 3 5]
 [2 4 6]
 [5 6 7]]


In [48]:
for room in arr_3d:
    print("Inside Room",room)
    for row in room:
        print("Inside room:{} row ".format(row))
        for col in row:
            print("col values",col)
      

Inside Room [[1 3 5]
 [2 4 6]
 [5 6 7]]
Inside room:[1 3 5] row 
col values 1
col values 3
col values 5
Inside room:[2 4 6] row 
col values 2
col values 4
col values 6
Inside room:[5 6 7] row 
col values 5
col values 6
col values 7


In [58]:
#Multiplication,Addition,Subtraction in numpy
arr1=np.array(range(1,17,1))
arr1=arr1.reshape(4,4)
arr2=np.array(range(10,170,10))
arr2=arr2.reshape(4,4)
print("ARR 1",arr1)
print("ARR 2",arr2)

#Addition
arr1+arr2

ARR 1 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
ARR 2 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [60]:
#Sub
arr2-arr1

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [61]:
#Mul
arr2*arr1

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [62]:
arr1-arr2

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [63]:
np.subtract(arr1,arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [64]:
np.multiply(arr1,arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [65]:
#Dot product = matrix multiplication
arr1=np.array([[1,2],[3,5]])
arr2=np.array([[2,3],[4,5]])
np.dot(arr1,arr2)


array([[10, 13],
       [26, 34]])

In [66]:
np.multiply(arr1,arr2)


array([[ 2,  6],
       [12, 25]])

In [67]:
a1=np.array([[2,3,6],[4,5,7]])
a2=np.array([[2,5,6],[7,8,7],[9,10,8]])
np.dot(a1,a2)

#2x3 and 3x3.Resultant matrix=2x3

array([[ 79,  94,  81],
       [106, 130, 115]])

In [70]:
#Join numpy array 
a1=np.array([2,3,6])
a2=np.array([2,5,6])
np.stack((a1,a2),axis=0)

array([[2, 3, 6],
       [2, 5, 6]])

In [71]:
np.stack((a1,a2),axis=1)
#axis will be 0 or 1 - row or column

array([[2, 2],
       [3, 5],
       [6, 6]])

In [76]:
a3=np.stack((a1,a2),axis=0)
a3

array([[2, 3, 6],
       [2, 5, 6]])

In [77]:
a3.T

array([[2, 2],
       [3, 5],
       [6, 6]])

In [78]:
np.sort(a3)

array([[2, 3, 6],
       [2, 5, 6]])